### PR TITLE
:wrench: Move from yarn to pnpm

### PR DESCRIPTION
**Pull request by UltiRequiem**
https://pnpm.io

### CODE REVIEW

**Comment by UltiRequiem** [comment]
Voy a arreglar la CI primero

**Comment by UltiRequiem** [comment]
This gonna have to be squished 😆

**Comment by UltiRequiem** [comment]
This pull request fixes the logout button too

**Review by Brian3647 — APPROVED** [review]
Looks good. Why do you choose pnpm over yarn?

**Comment by UltiRequiem** [comment]
> Looks good. Why do you choose pnpm over yarn?

nice

**Pull request merged**
